2aZXezLqBOUh2vOrPxSDHtk49ry_51D44xXFnoBwjyrNwxsYS: Setup Linux Remote Desktop

on: [push]

jobs:
  setup-rdp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install desktop environment and xrdp
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xrdp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          echo "xfce4-session" > ~/.xsession

      - name: Setup RDP user
        run: |
          if id "runneradmin" &>/dev/null; then
              echo "User runneradmin already exists"
          else
              sudo adduser --disabled-password --gecos "" runneradmin
              echo "runneradmin:@cyb3king" | sudo chpasswd
              sudo adduser runneradmin sudo
              sudo mkdir -p /home/runneradmin/.xsession
              echo "xfce4-session" > /home/runneradmin/.xsession
              sudo chown runneradmin:runneradmin /home/runneradmin/.xsession
          fi

      - name: Install Google Chrome Remote Desktop
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt-get install -f -y
          sudo apt-get install -y xfce4-session

      - name: Configure Google Remote Desktop
        run: |
          sudo -u runneradmin bash -c 'DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AcvDMrBLaY62yd4UgFGqLgoWC0okmE47aZJjD_lZKzK_pAuT9RUNJ_87VYJ3m0MTVHgf9w" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)'

      - name: Set the PIN for Google Remote Desktop
        run: |
          echo "123456" | sudo tee /opt/google/chrome-remote-desktop/pin.conf > /dev/null
          sudo systemctl restart chrome-remote-desktop@$USER

      - name: Create RDP file
        run: |
          echo 'full address:s:127.0.0.1:3389' > ~/linux-remote-desktop.rdp
          echo 'username:s:runneradmin' >> ~/linux-remote-desktop.rdp
          echo 'password:s:@cyb3king' >> ~/linux-remote-desktop.rdp
          echo 'server port:i:3389' >> ~/linux-remote-desktop.rdp
          echo 'screen mode id:i:2' >> ~/linux-remote-desktop.rdp
          echo 'session bpp:i:32' >> ~/linux-remote-desktop.rdp

      - name: Upload RDP file
        uses: actions/upload-artifact@v2
        with:
          name: linux-remote-desktop
          path: ~/linux-remote-desktop.rdp
